services:
  - type: web
    name: khoroch-deals-scraper
    env: docker
    autoDeploy: true
    healthCheckPath: /healthz
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"